// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfERZEqx8kptKPNcmZpxH-eKNzEE3-sEM',
    appId: '1:379713869708:web:599cf3561cc5c3cd3d68a9',
    messagingSenderId: '379713869708',
    projectId: 'flutter-crud-39b9c',
    authDomain: 'flutter-crud-39b9c.firebaseapp.com',
    storageBucket: 'flutter-crud-39b9c.firebasestorage.app',
    measurementId: 'G-SJ51790WZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOBkYuzKziDhYWXXxMVX_bGa9bHcAwZDQ',
    appId: '1:379713869708:android:ab951fc075f044333d68a9',
    messagingSenderId: '379713869708',
    projectId: 'flutter-crud-39b9c',
    storageBucket: 'flutter-crud-39b9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkxlLYQxp2j1hmXPJ62RmkZBlHb8lTfug',
    appId: '1:379713869708:ios:f8241f05f85491033d68a9',
    messagingSenderId: '379713869708',
    projectId: 'flutter-crud-39b9c',
    storageBucket: 'flutter-crud-39b9c.firebasestorage.app',
    iosBundleId: 'in.ram.crudflutter.crudFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkxlLYQxp2j1hmXPJ62RmkZBlHb8lTfug',
    appId: '1:379713869708:ios:f8241f05f85491033d68a9',
    messagingSenderId: '379713869708',
    projectId: 'flutter-crud-39b9c',
    storageBucket: 'flutter-crud-39b9c.firebasestorage.app',
    iosBundleId: 'in.ram.crudflutter.crudFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfERZEqx8kptKPNcmZpxH-eKNzEE3-sEM',
    appId: '1:379713869708:web:c0d613c11344aac73d68a9',
    messagingSenderId: '379713869708',
    projectId: 'flutter-crud-39b9c',
    authDomain: 'flutter-crud-39b9c.firebaseapp.com',
    storageBucket: 'flutter-crud-39b9c.firebasestorage.app',
    measurementId: 'G-1J3JNCMFFQ',
  );
}
